### ISSUE TITLE
Unable to upgrade AdvancedTomato [ERROR occured!]

### ISSUE THREAD

**Issue by jsdez** [Jackysi/advancedtomato#92]
Hello,
## when going to the following page http://192.168.1.1/#admin-upgrade.asp I get the blow error

SyntaxError: Unexpected token ILLEGAL
    at eval (native)
    at Function.x.extend.globalEval (http://192.168.1.1/js/jquery.min.js:2:4243)
    at x.fn.extend.domManip (http://192.168.1.1/js/jquery.min.js:3:21391)
    at x.fn.extend.append (http://192.168.1.1/js/jquery.min.js:3:18985)
    at null. (http://192.168.1.1/js/jquery.min.js:3:20357)
    at Function.x.extend.access (http://192.168.1.1/js/jquery.min.js:2:5780)
    at x.fn.extend.html (http://192.168.1.1/js/jquery.min.js:3:20020)
    at Object.TomatoAJAX.onCompleted (http://192.168.1.1/js/advancedtomato.js:231:29)
    at Object.XmlHttp.onReadyStateChange (http://192.168.1.1/tomato.js:1603:6)
##     at XMLHttpRequest. (http://192.168.1.1/tomato.js:1855:33)Unexpected token ILLEGAL

When I go to http://192.168.1.1/admin-upgrade.asp directly I get a page that allows me to insert an attachment but the upgrade button doesn't work.

I am on version Tomato Firmware 1.28.0000 -2.9-131 K26ARM USB AIO-64K
Router: Asus RT-AC68R/U

I have tried this on multiple browsers and OS, No difference.

**Comment by Jackysi** [comment]
You can not use pages directly e.g.: **/admin-upgrade.asp**. The above error is not really useful, could you click on error "SyntaxError" or any other link on TOP which will show actual faulty code? Since V3.0 that is possible I am just not sure which part of code is the actual error (the part of code that fails). 

There is another way to flash router, try **http://router:port/upgrade-plain.asp**. This is fail safe if something like above happens.

P.S.: Please include router model / firmware build in future please, without that I have no way of knowing what could be wrong.. E.g.: Asus RT-N66U - AIO build
